CREATE TABLE goals (
	id INTEGER UNSIGNED auto_increment NOT NULL,
	game_id INTEGER UNSIGNED NOT NULL,
	team_id INTEGER UNSIGNED NOT NULL,
	player_id INTEGER UNSIGNED NOT NULL,
	minute INTEGER UNSIGNED NOT NULL,
	half INTEGER UNSIGNED NOT NULL,
	type ENUM("normal", "og", "penalty"),
	FOREIGN KEY (team_id) REFERENCES teams(id),
	FOREIGN KEY (player_id) REFERENCES players(id),
	FOREIGN KEY (game_id) REFERENCES games(id),
	PRIMARY KEY (id)
) ENGINE=INNODB;