CREATE TABLE wc2010_venues (
	id INTEGER UNSIGNED auto_increment NOT NULL,
	name CHARACTER VARYING(32) NOT NULL,
	city CHARACTER VARYING(16) NOT NULL,
	capacity INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (id)
) ENGINE=INNODB;